#include "CkTestBridge_UserSettings.h"

// --------------------------------------------------------------------------------------------------------------------

// Nothing to implement — the CDO holds the persisted value and Get_ServeMode is generated by CK_PROPERTY_GET.
// This translation unit exists so the module has a compiled home for the settings class.

// --------------------------------------------------------------------------------------------------------------------
